language: node_js
node_js:
    - "0.10"

branches:
    only:
        - master

install:
    - npm install testem
    - npm install

cache:
    directories:
        - node_modules

script:
    - "gulp && ./node_modules/.bin/testem ci -f testem.json"
