sudo: false

language: node_js

node_js:
  - '6'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm config set spin false
  - npm config set loglevel http
  - npm install testem
  - npm install

script:
  - npm run travis
